-- Add new columns to profiles table
ALTER TABLE public.profiles
ADD COLUMN IF NOT EXISTS cpf text,
ADD COLUMN IF NOT EXISTS birth_date date,
ADD COLUMN IF NOT EXISTS job_title text,
ADD COLUMN IF NOT EXISTS department text,
ADD COLUMN IF NOT EXISTS manager_id uuid REFERENCES public.profiles(id),
ADD COLUMN IF NOT EXISTS employee_id bigint GENERATED BY DEFAULT AS IDENTITY,
ADD COLUMN IF NOT EXISTS gender text;

-- Add unique constraint to CPF per organization
ALTER TABLE public.profiles
ADD CONSTRAINT profiles_cpf_org_unique UNIQUE (cpf, organization_id);

-- Update handle_new_user function to include new fields
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger AS $$
BEGIN
  INSERT INTO public.profiles (
    id, 
    full_name, 
    role, 
    organization_id,
    cpf,
    birth_date,
    job_title,
    department,
    manager_id,
    gender
    -- employee_id is auto-generated
  )
  VALUES (
    new.id, 
    new.raw_user_meta_data->>'full_name',
    COALESCE(new.raw_user_meta_data->>'role', 'user'),
    (new.raw_user_meta_data->>'organization_id')::uuid,
    new.raw_user_meta_data->>'cpf',
    (new.raw_user_meta_data->>'birth_date')::date,
    new.raw_user_meta_data->>'job_title',
    new.raw_user_meta_data->>'department',
    (new.raw_user_meta_data->>'manager_id')::uuid,
    new.raw_user_meta_data->>'gender'
  );
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;
